name: CTFTime Discord Bot

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:


jobs:
  ctftime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt


      - name: Run CTFTime Discord Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python CTFtimeDiscordHooks.py \
            -w "$DISCORD_WEBHOOK" \
            -d 10
